name: PluginRemover
version: 1.4
main: zin\PluginRemover\Main
api: 5.0.0
src-namespace-prefix: zin\PluginRemover
commands:
  plremove:
    description: "Delete a plugin"
    permission: pl.remove
permissions:
  pl.remove:
    default: false
